language: c
script: make
compiler:
  - gcc
before_install:
  - test -n $CC && unset CC
dist: trusty
addons:
  sonarcloud:
    organization: "tbtimber-github" # the key of the org you chose at step #3
script:
  # other script steps might be done before running the actual analysis
  - sonar-scanner
